baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yusuf Yavuzyiğit'
publishDir = "docs"

theme = "quint"
summaryLength = 20

[[menus.main]]
name = 'GitHub'
url = 'https://github.com/yusufyavuzyigit'
